version: '3.9'
networks:
  cassandra:
services:
  cassandra-db-node-1:
    image: cassandra:3.11.10
    container_name: cassandra-db-node-1
    hostname: cassandra-db-node-1
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9042:9042"
    volumes:
      - /tmp/data/cassandra-db-node-1:/var/lib/cassandra
    environment: &environment
        CASSANDRA_SEEDS: "cassandra-db-node-1,cassandra-db-node-2"
        CASSANDRA_CLUSTER_NAME: SolarSystem
        CASSANDRA_DC: Mars
        CASSANDRA_RACK: West
        CASSANDRA_ENDPOINT_SNITCH: GossipingPropertyFileSnitch
        CASSANDRA_NUM_TOKENS: 128

  cassandra-db-node-2:
    image: cassandra:3.11.10
    container_name: cassandra-db-node-2
    hostname: cassandra-db-node-2
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9043:9042"
    volumes:
      - /tmp/data/cassandra-db-node-2:/var/lib/cassandra
    environment: *environment
    depends_on:
      cassandra-db-node-1:
        condition: service_healthy

  cassandra-db-node-3:
    image: cassandra:3.11.10
    container_name: cassandra-db-node-3
    hostname: cassandra-db-node-3
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces" ]
        interval: 5s
        timeout: 5s
        retries: 60
    networks:
      - cassandra
    ports:
      - "9044:9042"
    volumes:
      - /tmp/data/cassandra-db-node-3:/var/lib/cassandra
    environment: *environment
    depends_on:
      cassandra-db-node-2:
        condition: service_healthy